### ISSUE TITLE
How to use the project to calculate camera extrinsics.

### ISSUE THREAD

**Issue by Yuhuoo** [pointrix-project/msplat#5]
Hi, thanks for your nice work!

Could you provide a routine on how to optimize camera parameters? I've tried using _msplat.rasterizer()_ but haven't succeeded in optimizing the camera parameters. Even though I can see the camera parameter gradients updating properly, the loss doesn't decrease.

<img width="1221" alt="image" src="https://github.com/pointrix-project/msplat/assets/91204817/d2385394-e549-43a6-884c-492793f0bf43">

**Comment by yGaoJiany** [comment]
First, you need to create a trainable camera. It's not ideal to optimize directly on the rotation matrix; I recommend using quaternions for rotation instead. The _Roma_(https://naver.github.io/roma/) library can help convert between quaternions and rotation matrices easily and differentiably. 
Then, you need a new optimizer for your trainable camera to backward the loss.
Some issues might arise. Since a camera's gradient is accumulated from many points in the scene, numerical accuracy issues can occur when the number of points is particularly high. A possible solution is to randomly select only N points (10k might be a good choice) at each rendering to accumulate the gradient for the camera.
